global:
  chartPath: apps
  helmValues:
    - name: stage
      value: $STAGE
argocd-config:
  namespace: argocd
cert-manager:
  namespace: cert-manager
traefik:
  namespace: routing
  helmValues:
    - name: "traefik.deployment.replicas"
      value: "1"
storage-classes:
  namespace: storage
admin-dashboard:
  namespace: admin
kafka:
  namespace: kafka
basic-auth-gateway:
  namespace: routing
elastic-stack:
  namespace: monitoring