global:
  helmValues:
    - name: stage
      value: $STAGE
    - name: dns.host
      value: "admin.$STAGE-REPLACE_ME.iits.tech"
argocd-config:
  namespace: argocd
cert-manager:
  namespace: cert-manager
traefik:
  namespace: routing
  helmValues:
    - name: "traefik.deployment.replicas"
      value: "1"
#storage-classes:
#  namespace: storage
#admin-dashboard:
#  namespace: admin
#kafka:
#  namespace: kafka
#basic-auth-gateway:
#  namespace: routing